manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: guidoism
      url-base: https://github.com/guidoism
    - name: urob
      url-base: https://github.com/urob      
  projects:
    - name: zmk
      remote: guidoism # zmkfirmware
      revision: 82eed0f5ddb05fc244385e0ac05704fbdec0c3ee # d1ad34761a0a98fd8e36edbf978ebd4938797472
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: main
  self:
    path: config
