manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: guidoism
      url-base: https://github.com/guidoism
    - name: urob
      url-base: https://github.com/urob      
  projects:
    - name: zmk
      remote: guidoism # zmkfirmware
      revision: 6e03a0bb67d0b2fc12004b109cbbd8c5c1448a21 # d1ad34761a0a98fd8e36edbf978ebd4938797472
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: main
  self:
    path: config
