manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: guidoism
      url-base: https://github.com/guidoism
    - name: urob
      url-base: https://github.com/urob
    - name: ssbb
      url-base: https://github.com/ssbb
    - name: zzeneg
      url-base: https://github.com/zzeneg
  projects:
    - name: zmk
      remote: guidoism # zmkfirmware
      revision: feature/raw-hid-status # main
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: main
    - name: zmk-listeners
      remote: ssbb
      revision: v1
    - name: zmk-raw-hid
      remote: zzeneg
      revision: main
  self:
    path: config
