manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: guidoism
      url-base: https://github.com/guidoism
    - name: urob
      url-base: https://github.com/urob      
  projects:
    - name: zmk
      remote: guidoism
      revision: urob
      import: app/west.yml
  self:
    path: config
